### ISSUE TITLE
How to catch exceptions correctly

### ISSUE THREAD

**Issue by c3rebro** [islog/liblogicalaccess-swig#3]
Hello,

When i call a method authenticate() with a wrong key, or try to call createApplication() with an appid that already exist, an error is thrown.

However in difference to the older 1.87.8 library the thrown errorcodes all are related to mscorlib. So the HResult are all the same.

Maybe i do it the wrong way. How do i catch the correct exception codes?

A simple
```
try{

}
catch (Exception e){

}
```

does not produce the expected result.

**Comment by Maxhy** [comment]
It depends the kind of exception, but usually most typed LLA exceptions are now `LibLogicalAccessException` or `CardException`

**Comment by Maxhy** [comment]
I guess this can be closed, otherwise feel free to comment.
